= CURIOSITÉS JUDICIAIRES ET HISTORIQUES DU MOYEN ÂGE. PROCÈS CONTRE LES ANIMAUX.
:author: Émile Agnel 
:description: Un livre d'Émile Agnel
:keywords: livre, français, judiciaire, animaux 


Les singularités judiciaires sont nombreuses et variées au moyen âge, et souvent les magistrats interviennent dans des circonstances si bizarres, que nous avons peine à comprendre, de nos jours, comment ces graves organes de la justice ont pu raisonnablement figurer dans de telles affaires.

Toutefois notre but n'est pas de critiquer ici des usages plus ou moins absurdes, mais d'en constater simplement l'existence.
Nous bornons notre rôle à raconter les faits, sauf au lecteur à en tirer lui-même les conséquences.

Plusieurs siècles nous séparent de l'époque dont nous cherchons à étudier les mœurs et les idées, qui forment avec les nôtres de si étranges disparates; aussi n'est-ce qu'après de scrupuleuses recherches faites dans les ouvrages des jurisconsultes et des historiens les plus respectables, que nous avons osé présenter cette rapide esquisse.

Au moyen âge on soumettait à l'action de la justice tous les faits condamnables de quelque être qu'ils fussent émanés, même des animaux.

L'histoire de la jurisprudence nous offre à cette époque de nombreux exemples de procès dans lesquels figurent des taureaux, des vaches, des chevaux, des porcs, des truies, des coqs, des rats, des mulots, des limaces, des fourmis, des chenilles, sauterelles, mouches, vers et sangsues.

La procédure que l'on avait adoptée pour la poursuite de ces sortes d'affaires revêtait des formes toutes spéciales; cette procédure était différente, suivant la nature des animaux qu'il s'agissait de poursuivre.

Si l'animal auteur d'un délit—tel par exemple qu'un porc, une truie, un bœuf—peut être saisi, appréhendé au corps, il est traduit devant le tribunal criminel ordinaire, il y est assigné personnellement; mais s'il s'agit d'animaux sur lesquels on ne peut mettre la main, tels que des insectes ou d'autres bêtes nuisibles à la terre, ce n'est pas devant le tribunal criminel ordinaire que l'on traduira ces délinquants insaisissables, mais devant le tribunal ecclésiastique, c'est-à-dire devant l'officialité.